version: '3'

services:
  fpm:
    deploy:
      replicas: 6
      update_config:
        parallelism: 2
        delay: 5s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
          # - engine.labels.operatingsystem == ubuntu 18.04
      resources:
        limits:
          cpus: '0.50'
          memory: 128M