version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile_server
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
    container_name: dockernerds_server
    depends_on:
      - db
    volumes:
      - ./data/www/:/home/serveruser/vhosts:delegated
  fpm:
    build:
      context: ./
      dockerfile: ./Dockerfile_fpm
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
    container_name: dockernerds_fpm
    volumes:
      - ./data/www/:/home/serveruser/vhosts:delegated
  db:
    image: mariadb:10.3
    container_name: dockernerds_db
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - db-logs:/var/log/mysql
      - ./data/app_config/db:/etc/mysql/conf.d:delegated
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      dockernerds_net:
  phpmyadmin:
    container_name: dockernerds_phpmyadmin